apiVersion: v1
kind:       PersistentVolumeClaim
metadata:
  namespace: bloggin-system
  name:      bloggin-claim-postgres
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi